CREATE DATABASE IF NOT EXISTS banana;
CREATE USER IF NOT EXISTS 'banana'@'%' IDENTIFIED BY 'k+B68nC/XgS5Z3C1YITDv1ySULfkPuErYjc/st+kqPc=';
GRANT ALL PRIVILEGES ON banana.* TO 'banana'@'%';
FLUSH PRIVILEGES;
